[project]
name = "diffusion-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "h5py>=3.11.0",
    "imageio-ffmpeg>=0.6.0",
    "ipykernel>=7.1.0",
    "ipython>=9.8.0",
    "matplotlib>=3.10.7",
    "numba>=0.63.0",
    "numpy>=2.3.5",
    "pandas>=3.0.3",
    "plotly>=6.9.0",
    "pytest>=9.0.2",
    "scipy>=1.16.3",
    "tqdm>=4.67.1",
]

[project.scripts]
diffusion-sim = "diffusion_sim.cli:main"
diffusion-density = "diffusion_sim.density_cli:main"
diffusion-energy = "diffusion_sim.energy_cli:main"

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[dependency-groups]
dev = [
    "notebook>=7.5.1",
]
